Group 5 <br>
Python Implementation => Deliverable


## Implementing a ML model to predict the category of the Product using the name of the Product.

In [ ]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
import nltk
from nltk.corpus import wordnet
from nltk.corpus import stopwords
from gensim.models import Word2Vec,KeyedVectors
from sklearn.preprocessing import LabelEncoder
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

###Data Input

In [ ]:
mapping_data = pd.read_csv("/content/drive/MyDrive/QUANTUM ANALYTICA- CANNABIS/product_category_mappings_new_1.csv")

###Data Cleaning

In [ ]:
#removing special characters and digits form the product name column.
mapping_data['product_name'] = mapping_data['product_name'].str.replace(r'\d+','')

#retaining only english keywords in product names
for i, row in mapping_data.iterrows():
    text_t = ' '.join([w for w in row['product_name'].split() if wordnet.synsets(w)])
    mapping_data.at[i,'product_name'] = text_t

#converting the product_names to lower and remving stopwords if any
for i, row in mapping_data.iterrows():
    word_list_t = row['product_name'].lower().split() 
    filtered_words = [word for word in word_list_t if word not in stopwords.words('english')]
    text_t = ' '.join(filtered_words)
    mapping_data.at[i,'product_name']= text_t

#Tokenization
mapping_data['product_names_token'] = mapping_data['product_name'].apply(lambda x: x.split())

### Loading Pre Trained Word Embedding Model

In [ ]:
#loading the Google Word Embeddings
!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

#Load the word2vec pre trained Model to get the word embeddings for each token
model = KeyedVectors.load_word2vec_format('./GoogleNews-vectors-negative300.bin.gz',binary=True,limit=1000000)

--2021-06-27 13:44:28--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.199.8
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.199.8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  66.6MB/s    in 22s     

2021-06-27 13:44:51 (70.2 MB/s) - ‘GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]



### Data Preparation

In [ ]:
def token_check(x,model):
  """
  1.Check if the token exists in the word2vec model vocab. 
  2.Check if the length of the token is greater than 3 
  """
  token_list=[]
  count_dict= {}
  for i in x:
      if i not in count_dict and i in model.vocab:
        count_dict[i] = 1
      #if len(i) > 3 and i in model.vocab:
        token_list.append(i)
      else:
          continue
  return token_list

def word_vector(tokens,size,model):
  """Averaging the word vectors"""
  vec = np.zeros(size).reshape((1, size))
  count = 0
  for word in tokens:
    vec += model[word].reshape((1, size))
    count += 1.
  if count != 0:
      vec /= count
  return vec

In [ ]:
mapping_data['product_names_token'] = mapping_data['product_names_token'].apply(lambda x:token_check(x,model))
mapping_data['length_of_tokens'] = mapping_data['product_names_token'].apply(lambda x: len(x))

new_data = mapping_data[mapping_data['length_of_tokens'] > 0]
new_data.reset_index(drop=True, inplace=True)
wordvec_arrays = np.zeros((len(new_data.product_names_token),300))

for i in range(len(new_data.product_names_token)):
  wordvec_arrays[i,:] = word_vector(new_data.product_names_token[i],300,model)

vectorized_df = pd.DataFrame(wordvec_arrays)

In [ ]:
vectorized_df.head()

0         1         2    ...       297       298       299
0 -0.017822 -0.007568  0.176758  ... -0.021606  0.035706 -0.252441
1 -0.112305 -0.285645  0.063354  ...  0.006836 -0.165039  0.044312
2 -0.018311  0.018433  0.126526  ... -0.002441  0.082092 -0.076973
3 -0.007324  0.156738  0.156738  ... -0.062561  0.144287  0.009277
4  0.121094 -0.046875  0.035889  ... -0.040039  0.259766  0.250000

[5 rows x 300 columns]

### Data PreProcessing

In [ ]:
#one hot encoding the target product categories
target_one_hot_encoded = pd.get_dummies(new_data['category'])

# creating instance of labelencoder
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
new_data['category_code'] = labelencoder.fit_transform(new_data['category'])

#merging the vectorized and one hot encoded dataframes.
dataset_final = pd.merge(vectorized_df,new_data['category_code'],left_index=True, right_index=True)

#random shuffling the data before splitting
dataset_final_shuffled = dataset_final.reindex(np.random.permutation(dataset_final.index))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
dataset_final_shuffled.head()

0         1         2  ...       298       299  category_code
3586 -0.232422  0.237305  0.179688  ...  0.196289 -0.114746              5
2968 -0.157251 -0.003418  0.095020  ...  0.107593 -0.015039              5
9461 -0.115804  0.092794  0.142253  ... -0.123861  0.155599              3
4896 -0.107962  0.001011  0.042201  ...  0.190988 -0.087306              5
5096 -0.462891  0.024170  0.223633  ...  0.400391 -0.039551              2

[5 rows x 301 columns]

## Modeling

### Support Vector Machine

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

target = target_one_hot_encoded.columns
X = dataset_final_shuffled.drop('category_code', axis=1)
y = dataset_final_shuffled['category_code']

X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.75,test_size=0.25,random_state=101)

model = SVC()
param_grid = { 'C':[0.1,1],'kernel':['rbf'],'gamma': [1, 0.1]}
grid = GridSearchCV(model,param_grid)
grid.fit(X_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1], 'gamma': [1, 0.1], 'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
print(grid.best_params_)
print(grid.score(X_test,y_test))

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}
0.7546481954064892


In [ ]:
print(grid.best_params_)
print(grid.score(X_train,y_train))

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}
0.9212253829321663


In [ ]:
print(grid)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1], 'gamma': [1, 0.1], 'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)


In [ ]:
# summarize the fit of the model
from sklearn import metrics
# make predictions
expected = y_train
predicted = grid.predict(X_train)

print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))


              precision    recall  f1-score   support

           0       0.96      0.78      0.86       415
           1       0.95      0.62      0.75       145
           2       0.92      0.43      0.59        76
           3       0.95      0.80      0.87       387
           4       0.89      0.95      0.92      1695
           5       0.98      0.99      0.99      2342
           6       0.84      0.93      0.88       804
           7       0.89      0.98      0.94      1041
           8       1.00      0.40      0.57        53
           9       0.90      0.86      0.88       912
          10       1.00      0.93      0.97        46
          11       0.95      0.50      0.66        40
          12       0.96      0.95      0.95       157
          13       0.99      0.86      0.92       113

    accuracy                           0.92      8226
   macro avg       0.94      0.79      0.84      8226
weighted avg       0.92      0.92      0.92      8226

[[ 323    4    0    0    

### Linear Discriminant Analysis

In [ ]:
# evaluate a lda model on the dataset
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
# grid search solver for lda
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
#splitting of data
from sklearn.model_selection import train_test_split

target = target_one_hot_encoded.columns
X = dataset_final_shuffled.drop('category_code', axis=1)
y = dataset_final_shuffled['category_code']

X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.75,test_size=0.25,random_state=101)

# define model
model = LinearDiscriminantAnalysis()

# define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=10, random_state=1)

# define grid
grid = dict()
grid['solver'] = ['svd', 'lsqr', 'eigen']
# define search
search = GridSearchCV(model, grid, scoring='accuracy', cv=cv, n_jobs=-1)
# perform the search
results = search.fit(X_train, y_train)

In [ ]:
# summarize
print('Mean Accuracy: %.3f' % results.best_score_)
print('Config: %s' % results.best_params_)

Mean Accuracy: 0.664
Config: {'solver': 'lsqr'}


In [ ]:
results.score(X_test,y_test)

0.6616842872767044

### Gradient Boosting Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
import pandas as pd
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import auc, accuracy_score, roc_auc_score, roc_curve
from sklearn.model_selection import GridSearchCV

estimator = lgb.LGBMClassifier(boosting_type='gbdt', 
                               learning_rate = 0.125, 
                               metric = 'multiclass', n_estimators = 20,
                               num_leaves = 38)

param_grid = {
    'n_estimators': [x for x in [75,100]],
    'learning_rate': [0.01,0.1,0.2],
    'num_leaves': [5,10],
    'boosting_type' : ['gbdt'],
    'objective' : ['multiclass'],
    'metric': ['multiclass'],
    'lambda_l1' : [0.10],
    'lambda_l2' : [0.20],
    'random_state' : [501]}

gridsearch = GridSearchCV(estimator, param_grid)

gridsearch.fit(X_train, y_train.values.ravel(),eval_set = [(X_test, y_test)],eval_metric = ['multi_logloss'],early_stopping_rounds = 10)

print('Best parameters found by grid search are:', gridsearch.best_params_)

Streaming output truncated to the last 5000 lines.
[57]	valid_0's multi_logloss: 1.68057	valid_0's multi_logloss: 1.68057
[58]	valid_0's multi_logloss: 1.67649	valid_0's multi_logloss: 1.67649
[59]	valid_0's multi_logloss: 1.67253	valid_0's multi_logloss: 1.67253
[60]	valid_0's multi_logloss: 1.66843	valid_0's multi_logloss: 1.66843
[61]	valid_0's multi_logloss: 1.66453	valid_0's multi_logloss: 1.66453
[62]	valid_0's multi_logloss: 1.66065	valid_0's multi_logloss: 1.66065
[63]	valid_0's multi_logloss: 1.65679	valid_0's multi_logloss: 1.65679
[64]	valid_0's multi_logloss: 1.65279	valid_0's multi_logloss: 1.65279
[65]	valid_0's multi_logloss: 1.64893	valid_0's multi_logloss: 1.64893
[66]	valid_0's multi_logloss: 1.64498	valid_0's multi_logloss: 1.64498
[67]	valid_0's multi_logloss: 1.64096	valid_0's multi_logloss: 1.64096
[68]	valid_0's multi_logloss: 1.63719	valid_0's multi_logloss: 1.63719
[69]	valid_0's multi_logloss: 1.6333	valid_0's multi_logloss: 1.6333
[70]	valid_0's multi_logloss

In [ ]:
gbm = lgb.LGBMClassifier(boosting_type= 'gbdt', lambda_l1= 0.1, lambda_l2= 0.2,learning_rate= 0.2, metric= 'multiclass', n_estimators = 100, num_leaves = 10,objective= 'multiclass', random_state= 501)

gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric=['multiclass'],
early_stopping_rounds=20)


[1]	valid_0's multi_logloss: 1.84723
Training until validation scores don't improve for 20 rounds.
[2]	valid_0's multi_logloss: 1.73949
[3]	valid_0's multi_logloss: 1.65169
[4]	valid_0's multi_logloss: 1.58072
[5]	valid_0's multi_logloss: 1.51868
[6]	valid_0's multi_logloss: 1.46674
[7]	valid_0's multi_logloss: 1.41964
[8]	valid_0's multi_logloss: 1.37827
[9]	valid_0's multi_logloss: 1.34367
[10]	valid_0's multi_logloss: 1.31045
[11]	valid_0's multi_logloss: 1.28046
[12]	valid_0's multi_logloss: 1.25366
[13]	valid_0's multi_logloss: 1.22946
[14]	valid_0's multi_logloss: 1.20829
[15]	valid_0's multi_logloss: 1.18746
[16]	valid_0's multi_logloss: 1.16869
[17]	valid_0's multi_logloss: 1.15324
[18]	valid_0's multi_logloss: 1.13798
[19]	valid_0's multi_logloss: 1.12339
[20]	valid_0's multi_logloss: 1.10764
[21]	valid_0's multi_logloss: 1.09362
[22]	valid_0's multi_logloss: 1.08091
[23]	valid_0's multi_logloss: 1.07094
[24]	valid_0's multi_logloss: 1.05961
[25]	valid_0's multi_logloss: 1.048

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', lambda_l1=0.1, lambda_l2=0.2,
               learning_rate=0.2, max_depth=-1, metric='multiclass',
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=10,
               objective='multiclass', random_state=501, reg_alpha=0.0,
               reg_lambda=0.0, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [ ]:
gbm.score(X_train,y_train)

0.9337466569414054

In [ ]:
gbm.score(X_test,y_test)

0.7305869485964273

### Random Forest Model

In [ ]:
#splitting of data
from sklearn.model_selection import train_test_split

target = target_one_hot_encoded.columns
X = dataset_final_shuffled.drop('category_code', axis=1)
y = dataset_final_shuffled['category_code']

X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.75,test_size=0.25,random_state=101)

In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7149106817353262


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.54      0.13      0.22       141
           1       0.42      0.22      0.29        45
           2       0.00      0.00      0.00        31
           3       0.68      0.32      0.44       134
           4       0.62      0.82      0.70       571
           5       0.83      0.96      0.89       779
           6       0.64      0.50      0.56       269
           7       0.72      0.86      0.78       355
           8       0.75      0.19      0.30        16
           9       0.69      0.63      0.66       300
          10       1.00      0.14      0.25        14
          11       0.25      0.11      0.15         9
          12       0.77      0.70      0.73        43
          13       1.00      0.31      0.47        36

    accuracy                           0.71      2743
   macro avg       0.64      0.42      0.46      2743
weighted avg       0.70      0.71      0.69      2743



In [ ]:
 print(confusion_matrix(y_test, y_pred))

[[ 19   3   0   0  17  16   3  76   0   1   0   0   6   0]
 [  3  10   0   0   7   4   0  21   0   0   0   0   0   0]
 [  0   0   0   0  23   4   0   0   0   3   0   1   0   0]
 [  1   0   0  43  69  17   2   2   0   0   0   0   0   0]
 [  1   0   1  15 467  36  15   5   1  28   0   2   0   0]
 [  0   0   0   0  22 746   4   1   0   5   0   0   1   0]
 [  0   2   0   3  38  36 135   6   0  48   0   0   1   0]
 [  7   9   0   0  16   8   9 304   0   1   0   0   1   0]
 [  0   0   0   0  12   0   1   0   3   0   0   0   0   0]
 [  0   0   0   2  51  14  40   3   0 190   0   0   0   0]
 [  0   0   0   0   8   3   0   1   0   0   2   0   0   0]
 [  0   0   0   0   8   0   0   0   0   0   0   1   0   0]
 [  4   0   0   0   2   7   0   0   0   0   0   0  30   0]
 [  0   0   1   0  15   3   1   4   0   1   0   0   0  11]]


####Hyper Parameter Tuning

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from pprint import pprint

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]

# Number of features to consider at every split
max_features = ['auto', 'sqrt']

# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)

# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]

# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]

# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [ ]:
# Use the random grid to search for best hyperparameters
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = clf, param_distributions = random_grid, n_iter = 5, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train,y_train)

Fitting 3 folds for each of 5 candidates, totalling 15 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:691: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
[Parallel(n_jobs=-1)]: Done  15 out of  15 | elapsed: 16.1min finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [ ]:
rf_random.best_params_

{'bootstrap': False,
 'max_depth': 60,
 'max_features': 'auto',
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 600}

In [ ]:
### Best parameters and fit in the model
best_random = rf_random.best_estimator_

In [ ]:
best_random.fit(X_train,y_train)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=60, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred = best_random.predict(X_test)

# Model Accuracy, how often is the classifier correct..
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7276704338315713


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.15      0.23       141
           1       0.44      0.24      0.31        45
           2       0.00      0.00      0.00        31
           3       0.70      0.33      0.45       134
           4       0.65      0.83      0.73       571
           5       0.84      0.97      0.90       779
           6       0.67      0.54      0.60       269
           7       0.72      0.85      0.78       355
           8       0.60      0.19      0.29        16
           9       0.71      0.65      0.68       300
          10       1.00      0.07      0.13        14
          11       0.20      0.11      0.14         9
          12       0.79      0.72      0.76        43
          13       1.00      0.28      0.43        36

    accuracy                           0.73      2743
   macro avg       0.63      0.42      0.46      2743
weighted avg       0.71      0.73      0.70      2743



In [ ]:
y_pred

array([ 5,  5,  7, ...,  4, 13,  5])

###Predictions over Products Data

In [ ]:
### import product mappings
mapping_data = pd.read_csv("/content/drive/MyDrive/QUANTUM ANALYTICA- CANNABIS/northeastern_product_data.csv")

In [ ]:
#removing special characters and digits form the product name column.
mapping_data['product_name'] = mapping_data['product_name'].str.replace(r'\d+','')

In [ ]:
mapping_data = mapping_data.applymap(str)

#retaining only english keywords in product names
for i, row in mapping_data.iterrows():
    text_t = ' '.join([w for w in row['product_name'].split() if wordnet.synsets(w)])
    mapping_data.at[i,'product_name'] = text_t

#converting the product_names to lower and remving stopwords if any
for i, row in mapping_data.iterrows():
    word_list_t = row['product_name'].lower().split() 
    filtered_words = [word for word in word_list_t if word not in stopwords.words('english')]
    text_t = ' '.join(filtered_words)
    mapping_data.at[i,'product_name']= text_t

#Tokenization
mapping_data['product_names_token'] = mapping_data['product_name'].apply(lambda x: x.split())

#vectorization
def token_check(x,model):
  """
  1.Check if the token exists in the word2vec model vocab. 
  2.Check if the length of the token is greater than 3 
  """
  token_list=[]
  count_dict= {}
  for i in x:
      if i not in count_dict and i in model.vocab:
        count_dict[i] = 1
      #if len(i) > 3 and i in model.vocab:
        token_list.append(i)
      else:
          continue
  return token_list

def word_vector(tokens,size,model):

  """Averaging the word vectors"""
  
  vec = np.zeros(size).reshape((1, size))
  count = 0
  for word in tokens:
    vec += model[word].reshape((1, size))
    count += 1.
  if count != 0:
      vec /= count
  return vec


#loading the Google Word Embeddings
!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

#Load the word2vec pre trained Model to get the word embeddings for each token
model = KeyedVectors.load_word2vec_format('./GoogleNews-vectors-negative300.bin.gz',binary=True,limit=1000000)

mapping_data['product_names_token'] = mapping_data['product_names_token'].apply(lambda x:token_check(x,model))

--2021-06-27 04:17:26--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.72.102
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.72.102|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.



In [ ]:
mapping_data['length_of_tokens'] = mapping_data['product_names_token'].apply(lambda x: len(x))
new_data = mapping_data[mapping_data['length_of_tokens'] > 0]

In [ ]:
new_data.reset_index(drop=True, inplace=True)
wordvec_arrays = np.zeros((len(new_data.product_names_token),300))

for i in range(len(new_data.product_names_token)):
  wordvec_arrays[i,:] = word_vector(new_data.product_names_token[i],300,model)

vectorized_df = pd.DataFrame(wordvec_arrays)

In [ ]:
vectorized_df.head()

0         1         2    ...       297       298       299
0  0.104980  0.018433  0.008972  ...  0.092285  0.061035 -0.132812
1  0.088867  0.077555  0.028158  ...  0.040609  0.234029 -0.095490
2  0.001465  0.006775  0.201843  ...  0.116760  0.062134 -0.127441
3  0.012492  0.031169  0.193522  ...  0.258464 -0.175496 -0.076335
4  0.059692  0.122803  0.234863  ... -0.066895 -0.090088  0.150787

[5 rows x 300 columns]

In [ ]:
final_pred = clf.predict(vectorized_df)
final_pred

array([ 6,  5, 10, ...,  5,  5,  6])

In [ ]:
new_data['product_category_predicted'] = labelencoder.inverse_transform(final_pred)
new_data.to_csv(f'/content/drive/MyDrive/northeastern_product_data_predicted.csv', columns=new_data.columns,sep=",",quotechar='"',index=False,quoting=csv.QUOTE_ALL)